name: "Get and Cache Dependencies"
description: "Get the dependancies (use YARN) and cache them to speed up the workflow"
runs:
  using: 'composite'
  steps:
    # add cache dependancies to speed up workflow
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: deps-node-modules-${{hashFiles('**/yarn.lock')}}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile
      shell: bash