name: Run Project Tests
on: [push, workflow_dispatch] # this means that the workflow will run on every push to the repository and also it can be triggered manually from the Actions tab in the GitHub repository

jobs:
    run_lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v6
            
            # add cache dependancies to speed up workflow
            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                path: ~/.cache/yarn
                key: deps-node-modules-${{hashFiles('**/yarn.lock')}}

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run lint
              run: yarn lint

    run_tests: #the name is upto you, it could be anything
        needs: run_lint 
        runs-on: ubuntu-latest
        steps:
            - name: Get code
            # USES: used to run a certain action, in this case we want to use the checkout action to get the code of the repository
              uses: actions/checkout@v6
            #   for configuration
            #   with:
                # ....
            - name: Cache dependencies
              uses: actions/cache@v5
              with:
                path: ~/.cache/yarn
                key: deps-node-modules-${{hashFiles('**/yarn.lock')}}
            - name: Install dependencies
                # yarn install === yarn ci, but yarn ci is more safe and faster because it doesn't update the lock file and doesn't check for new versions of packages, it just installs the exact versions specified in the lock file
              run: yarn install --frozen-lockfile

            - name: Run tests
              run: yarn test

            - name: Upload test report
              uses: actions/upload-artifact@v4
              with:
                name: test-report-file
                path: test.json

            #   SECOND JOB ACTION
    deployment_project: #the name is upto you, it could be anything
        needs: run_tests #this make the second job (deployment_project) runs after the first job (run_tests) finished and successed
        runs-on: ubuntu-latest #every job have to have its own runner
        steps:
            - name: Get code
              uses: actions/checkout@v6

            - name: Cache dependencies
              id: yarn-cache-dir-path
              uses: actions/cache@v5
              with:
                path: ~/.cache/yarn
                key: deps-node-modules-${{hashFiles('**/yarn.lock')}}

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Download Artifact
              uses: actions/download-artifact@v8
              with:
                name: test-report-file. #should be the same as the name of Upload Artifact at previos job
            
            - name: Print output content
              run : ls

            - name: Deploy the project
              run: echo "Deploying the project..."